### ISSUE TITLE
Discord?

### ISSUE THREAD

**Issue by mheidrich** [chanzer0/PGA-DFS-Tools#11]
First, thank you for sharing this (and other) tools for free. Beyond providing tremendous utility,the process and approach provides a helpful way to think about DFS.

Second, is there a discord or place where people are discussing best practices, potential updates,etc.?

**Comment by chanzer0** [comment]
Glad you are enjoying the tools. We don't have a dedicated community for specifically these tools, although in the future I could see that being a possibility. 

For now we're focused on improving the tools

**Comment by bjungwirth** [comment]
> 

Hey, we've gone ahead and created a discord community: https://discord.gg/KeQmPhHN
