### ISSUE TITLE
name 'PGA_Optimizer' is not defined

### ISSUE THREAD

**Issue by toonice17** [chanzer0/PGA-DFS-Tools#3]
Hey guys thanks for putting out some tools to play with im having trouble getting passed this step. I was following along with the readme and the youtube tutorial but im stuck. every time i try to run an opto i get the following error message.

PS C:\Users\H\Desktop\PGA-DFS-Tools-main\src> python .\main.py dk opto 1000 1
Traceback (most recent call last):
  File "C:\Users\H\Desktop\PGA-DFS-Tools-main\src\main.py", line 59, in <module>
    main(sys.argv)
  File "C:\Users\H\Desktop\PGA-DFS-Tools-main\src\main.py", line 21, in main
    opto = PGA_Optimizer(site, num_lineups, num_uniques)
           ^^^^^^^^^^^^^
NameError: name 'PGA_Optimizer' is not defined

**Comment by chanzer0** [comment]
The optimizer will be implemented in due time, this repo is still a bit of a work in progress

**Comment by toonice17** [comment]
Thanks, sorry for double posting the same question :( i saw the other question right after i posted mine
