### ISSUE TITLE
Opto - Total Pts Error

### ISSUE THREAD

**Issue by toonice17** [chanzer0/PGA-DFS-Tools#5]
Figured id give the opto a shot tonight. Ran into this error, my first thought was it could be a naming error but nothing jumped out at me when i looked through the dk data. I was hoping i was gonna solve this one :(

PS C:\Users\H\Desktop\PGA-DFS-Tools-main\src> python .\main.py dk opto 1000 1
['.\\main.py', 'dk', 'opto', '1000', '1']
Traceback (most recent call last):
  File "C:\Users\H\Desktop\PGA-DFS-Tools-main\src\main.py", line 61, in <module>
    main(sys.argv)
  File "C:\Users\H\Desktop\PGA-DFS-Tools-main\src\main.py", line 23, in main
    opto = PGA_Optimizer(site, num_lineups, num_uniques)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\H\Desktop\PGA-DFS-Tools-main\src\pga_optimizer.py", line 43, in __init__
    self.load_projections(projection_path)
  File "C:\Users\H\Desktop\PGA-DFS-Tools-main\src\pga_optimizer.py", line 130, in load_projections
    if float(row['Total Pts']) < self.projection_minimum:
             ~~~^^^^^^^^^^^^^
KeyError: 'Total Pts'

**Comment by bjungwirth** [comment]
think we have a discrepancy between required columns on the sim tool and required columns on the optimizer. try changing "Fpts" on the projections.csv to "Total Pts" and we'll get them synced up later

**Comment by chanzer0** [comment]
Yeah, the projections sheet for PGA uses the "Total Pts" column instead of "Fpts". We can try and make a better more universal format in the future

**Comment by toonice17** [comment]
Yes! Using this logic I was able to go through the rest of the errors on my own and adjust the names for each sheet. Mostly on the boom bust page.
Got it to run, Thanks guys! Have a good weekend.
