### ISSUE TITLE
Error when running dk sim

### ISSUE THREAD

**Issue by Scottw1105** [chanzer0/PGA-DFS-Tools#6]
(pga_dfs) PS C:\Conda\Projects\Portfolio\PGA-DFS-Tools-master\src> python .\main.py dk sim cid 1000
['.\\main.py', 'dk', 'sim', 'cid', '1000']
Contest payout structure loaded.
Traceback (most recent call last):
  File "C:\Conda\Projects\Portfolio\PGA-DFS-Tools-master\src\pga_gpp_simulator.py", line 106, in get_optimal
    problem.solve(plp.PULP_CBC_CMD(msg=0))
  File "C:\Conda\envs\pga_dfs\Lib\site-packages\pulp\pulp.py", line 1913, in solve
    status = solver.actualSolve(self, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Conda\envs\pga_dfs\Lib\site-packages\pulp\apis\coin_api.py", line 137, in actualSolve
    return self.solve_CBC(lp, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Conda\envs\pga_dfs\Lib\site-packages\pulp\apis\coin_api.py", line 146, in solve_CBC
    raise PulpSolverError(
pulp.apis.core.PulpSolverError: Pulp: cannot execute C:\Conda\envs\pga_dfs\Lib\site-packages\pulp\solverdir\cbc\win\64\cbc.exe cwd: C:\Conda\Projects\Portfolio\PGA-DFS-Tools-master\src

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Conda\Projects\Portfolio\PGA-DFS-Tools-master\src\main.py", line 61, in <module>
    main(sys.argv)
  File "C:\Conda\Projects\Portfolio\PGA-DFS-Tools-master\src\main.py", line 54, in main
    sim = PGA_GPP_Simulator(site, field_size, num_iterations, use_contest_data,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Conda\Projects\Portfolio\PGA-DFS-Tools-master\src\pga_gpp_simulator.py", line 72, in __init__
    self.get_optimal()
  File "C:\Conda\Projects\Portfolio\PGA-DFS-Tools-master\src\pga_gpp_simulator.py", line 109, in get_optimal
    len(self.num_lineups), self.num_lineups))
        ^^^^^^^^^^^^^^^^
AttributeError: 'PGA_GPP_Simulator' object has no attribute 'num_lineups'

Looks like something is up with Pulp but I can't see what's wrong.

**Comment by chanzer0** [comment]
It looks like whatever environment you're running this in (Conda?) doesn't have access to execute the `cbc.exe` file in the PuLP library.

The second error, `AttributeError: 'PGA_GPP_Simulator' object has no attribute 'num_lineups'` actually seems to be a legitimate error that wasn't caught yet, because we haven't had the PuLP solver fail on us yet. I can push up a quick fix for that

**Comment by Scottw1105** [comment]
I think was an issue on my end like you said, I removed the pulp library and reloaded it with PIP instead of Conda, worked like a charm. 
Also, just wanted to say, great work on this. I've created this almost exactly on my side last year but doesn't run nearly as fast. I have a great way (although brute force) to creating tournament gpp lines based on ownership percentage. 

I have a methodology of creating random lineups in large chunks (10's of thousands), then it recursively chooses a chunk of lineups that fits within the ownership% constraint. Fairly quick as well and you get a decently good representation of what the field would be based on the ownership% supplied.

**Comment by bjungwirth** [comment]
> I think was an issue on my end like you said, I removed the pulp library and reloaded it with PIP instead of Conda, worked like a charm. Also, just wanted to say, great work on this. I've created this almost exactly on my side last year but doesn't run nearly as fast. I have a great way (although brute force) to creating tournament gpp lines based on ownership percentage.
> 
> I have a methodology of creating random lineups in large chunks (10's of thousands), then it recursively chooses a chunk of lineups that fits within the ownership% constraint. Fairly quick as well and you get a decently good representation of what the field would be based on the ownership% supplied.

yeah this is still technically brute force to generate the field but it uses the power of the multiprocessing library to use all of your cpu to get the job done quick. the OG version of this (https://github.com/chanzer0/NBA-DFS-Tools) used to take minutes to generate lineups but now it's done in seconds. and the sim end is super quick as well because of numpy arrays
