### ISSUE TITLE
Key Error: Rory Mcilroy

### ISSUE THREAD

**Issue by toonice17** [chanzer0/PGA-DFS-Tools#8]
Hey Guys was trying the opto for this weeks tournament and it seems i screwed something up and the error isnt jumping out at me.

python .\main.py dk opto 100 1

['.\\main.py', 'dk', 'opto', '100', '1']
{'Scottie Scheffler': {'Fpts': 98.12, 'ID': 765, 'Salary': 11300, 'Name': 'Scottie Scheffler', 'RealID': 28368765, 'Ownership': 20.0, 'Optimal': 20.0, 'Leverage': 0.0, 'StdDev': 8.0, 'Ceiling': 98.12, 'Floor': 88.12, 'Top6%': 10.0, 'Withdraw': 0.0, 'Win%': 1.0, 'Swt6%': 15.0, 'Matchup': 'Travelers'}, 'Rory McIlroy': {'Fpts': 80.85, 'ID': 766, 'Salary': 10900, 'Name': 'Rory McIlroy', 'RealID': 28368766, 'Ownership': 19.9, 'Optimal': 20.0, 'Leverage': 0.0, 'StdDev': 8.0, 'Ceiling': 80.85, 'Floor': 70.85, 'Top6%': 10.0, 'Withdraw': 0.0, 'Win%': 1.0, 'Swt6%': 15.0, 'Matchup': 'Travelers'}, .... 

....Traceback (most recent call last):
  File "C:\Users\H\Desktop\PGA-DFS-Tools-main\src\main.py", line 61, in <module>
    main(sys.argv)
  File "C:\Users\H\Desktop\PGA-DFS-Tools-main\src\main.py", line 24, in main
    opto.optimize()
  File "C:\Users\H\Desktop\PGA-DFS-Tools-main\src\pga_optimizer.py", line 181, in optimize
    self.problem += plp.lpSum(lp_variables[player.replace('-', '#')]
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\H\AppData\Local\Programs\Python\Python311\Lib\site-packages\pulp\pulp.py", line 2281, in lpSum
    return LpAffineExpression().addInPlace(vector)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\H\AppData\Local\Programs\Python\Python311\Lib\site-packages\pulp\pulp.py", line 896, in addInPlace
    for e in other:
  File "C:\Users\H\Desktop\PGA-DFS-Tools-main\src\pga_optimizer.py", line 181, in <genexpr>
    self.problem += plp.lpSum(lp_variables[player.replace('-', '#')]
                              ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'Rory Mcilroy'

**Comment by chanzer0** [comment]
This is indicating you have a limit rule with Rory McIlroy that is either

1. A spelling mismatch between what you typed in the config.json file and the spelling of the name in the projections file
2. You have a limit rule for Rory and he's not in the projections

**Comment by toonice17** [comment]
Thank you. It must of been the captial i in his last name or something. I fooled around with it and it works
