### ISSUE TITLE
file format

### ISSUE THREAD

**Issue by bhibby** [chanzer0/PGA-DFS-Tools#9]
Hey, what are the proper file header format's for the PGA sim?

**Comment by bhibby** [comment]
how do I run this on a mac?

**Comment by chanzer0** [comment]
Running on a Mac will be very similar. The same steps apply

1. Install python
2. Clone or Download this repository
3. Add your data to the correct folder
4. Run a command from the src/ folder depending on what you want to do.

For more detail, I recommend checking out the README.md located at the root of this repository. It should cover in-depth how to get started. Most things will be the same or very similar if using a Mac
